Remove path cache related to avoid errors when clearing logs
The path cache leads to wrong judgement, i.e, it tells a log file
exists from the path cache while actually the file has been removed
physically. This leads to the error below which could be easily
triggered by user's manually CTRL-C during an ongoing monitoring:

OSError: [Errno 2] No such file or directory: '/root/logs/task.log'